### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by daviddias** [dignifiedquire/clean-documentation-theme#13]
> Taking https://ipfs.github.io/js-ipfs-bitswap as an example

# First look is that it feels empty

Or there is missing information of the theme is just not designed well for the type of content. I believe it is missing info.

![image](https://user-images.githubusercontent.com/1211152/29714507-6eadd35c-899b-11e7-806c-567768ea63ee.png)

# Clicking the <> url leads to 404

https://ipfs.github.io/js-ipfs-bitswap/[object%20Object]

# Return values only say the data type, not what is the actual value

# It would be great if custom DataTypes link to the repo of the data type

Othewise it is confusing for users.

![image](https://user-images.githubusercontent.com/1211152/29714555-a311fe34-899b-11e7-979e-9dd15a50260d.png)

**Comment by dignifiedquire** [comment]
> Return values only say the data type, not what is the actual value

What do you mean with this? We only know the parameter name and the type nothing else

**Comment by dignifiedquire** [comment]
> It would be great if custom DataTypes link to the repo of the data type

Sadly this is probably not doable without large efforts of using more types in our code base + large work in documentation.js

**Comment by diasdavid** [comment]
Couldn't we add a description after the var name on the jsdoc stuff?
![image](https://user-images.githubusercontent.com/1211152/29714698-254c0430-899c-11e7-99eb-0831ab112ebe.png)

**Comment by dignifiedquire** [comment]
Note: there are some obvious regressions in the latest version if you compare against an older version: https://multiformats.github.io/js-multibase

Yes you can write descriptions for variables and they should show up:

```js
* @param {CID} cid - the cool cid that we want to look up
```

**Comment by dignifiedquire** [comment]
> Clicking the <> url leads to 404

just published a version with fix for this
